matrix:
  include:
    - language: ruby
      ruby: 2.7.1
      script:
        - test/test_sample_ruby
    - language: go
      go: 1.15
      script:
        - testing
    - language: rust
      rust: 1.45.2
      script:
        - test
      