matrix:
  include:
    - language: ruby
      ruby: 2.7.1
      script:
        - ruby -I test test/test_sample_ruby.rs
    - language: go
      go: 1.15
      script:
        - go test ./...
    - language: rust
      rust: 1.45.2
      script:
        - cargo test --verbose
      