[package]
name = "gol"
version = "0.1.0"
authors = ["Shiva <shiva96b@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
